### ISSUE TITLE
AssertionError when run Quickstart in local envrionment

### ISSUE THREAD

**Issue by Opdoop** [DAI-Lab/fibber#34]
### Envrionment
* fibber version: 0.3.1
* Python version: 3.6.9
* Operating System: Ubuntu 18.04.5 LTS

### Description

Run Quickstart `(3) Create a Fibber object.`
Meet this bug:
```
`Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
  File "/usr/local/lib/python3.6/dist-packages/fibber/fibber.py", line 67, in __init__
    self._strategy.fit(trainset)
  File "/usr/local/lib/python3.6/dist-packages/fibber/paraphrase_strategies/asrs_strategy.py", line 296, in fit
    self._strategy_config["sim_metric"])
  File "/usr/local/lib/python3.6/dist-packages/fibber/metrics/metric_utils.py", line 99, in get_metric
    assert metric_name in self._metrics
AssertionError
```
Compared with code in `Colab`, I think this is caused by pass `"asrs_sim_metric": "CESimilarityMetric"` in `arg_dict`.
After delete `"asrs_sim_metric": "CESimilarityMetric"` in `arg_dict`. The bug goes away and gets the same result shown in `(4) You can also ask fibber to paraphrase your sentence.`
Currently, I don't know whether it's necessary to pass `asrs_sim_metric`. Should we remove  `"asrs_sim_metric": "CESimilarityMetric"`?

**Comment by Opdoop** [comment]
According to `asrs_strategy`, `CESimilarityMetric` is default value of `sim_metric`. So I think we could omit this `asrs_sim_metric`.
https://github.com/DAI-Lab/fibber/blob/ac278a06ae3204ba54d2ba2cbdd4dbe11f0bd745/fibber/paraphrase_strategies/asrs_strategy.py#L281
